export const SHELL_ACTION_NAMES = [
  "bg.clear", "bg.fill", "brush.bigger",
  "brush.fromSelection", "brush.smaller", "brushResize.capture",
  "brushResize.cycleDir", "brushResize.cycleSens", "canvas.crop",
  "canvas.rotate", "canvas.trim", "color.for",
  "color.pick", "color.replace", "color.setActive",
  "color.used", "cursor.cycleMode", "doc.new",
  "edit.copy", "edit.cut", "edit.delete",
  "edit.dropColorAt", "edit.floodAt", "edit.paste",
  "edit.redo", "edit.undo", "effect.bc",
  "effect.bc.edit", "effect.mono", "export.layer",
  "export.targetPng", "eyedropper.capture", "file.export",
  "file.exportPng", "file.exportPsd", "file.import",
  "fx.clipboardHasEffects", "fx.convert", "fx.copy",
  "fx.copyAll", "fx.delete", "fx.duplicate",
  "fx.edit", "fx.menu", "fx.panel",
  "fx.paste", "gallery.hide", "gallery.importDrop",
  "grid.open", "import.openFile", "lasso.cancel",
  "layer.add", "layer.center", "layer.delete",
  "layer.dropColorAt", "layer.fitShortSide", "layer.flipH",
  "layer.flipV", "layer.group", "layer.merge",
  "palette.add", "palette.addRgb", "palette.clearSelection",
  "palette.sort", "recolor.all", "recolor.start",
  "select.none", "selection.applyOp", "selection.byColor",
  "selection.copyLayer", "selection.fill", "selection.invert",
  "selection.layer", "selection.transform", "shading.clear",
  "shading.close", "shading.disable", "shading.enable",
  "shading.open", "shading.pickColors", "shading.reverse",
  "shading.setRamp", "text.applyPrefs", "text.editLayer",
  "text.ownsEditHistory",
  "toggle.symH", "toggle.symV", "tool.adjust",
  "tool.ellipse", "tool.eraser", "tool.fill",
  "tool.lasso", "tool.line", "tool.move",
  "tool.pencil", "tool.rect", "tool.select",
  "tool.shading", "tool.smudge", "tool.text", "transform.apply",
  "transform.cancel", "transform.enter", "transform.enterTargets",
  "ui.animation", "ui.brushLibrary", "ui.fontLibrary",
  "ui.layers", "view.fit", "view.realSize",
  "view.tile", "zoom.in", "zoom.out"
] as const;

export type ShellActionName = (typeof SHELL_ACTION_NAMES)[number];
